import { renderAbilityUseCard as renderCurrent, type AbilityUseCardViewModel } from "../../ui/components/ability/ability-use-card";
import type { ResolvedAbilityRoll } from "./config/ability-roll-config";
import { getAbilityDamageTypeLabel } from "./config/ability-roll-config";
export { AbilityUseChatCardService, renderPersistedAbilityCard } from "./ability-use-chat-card-service";
export type LegacyAbilityUseCardModel = { abilityName:string; abilityImage:string; actorName:string; activationLabel:string; description:string; resource:"PE"|"PD"; cost:number; passive:boolean; spentResource:boolean; resourceBefore:number; resourceAfter:number; rolls:ResolvedAbilityRoll[] };
export function renderAbilityUseCard(model: AbilityUseCardViewModel | LegacyAbilityUseCardModel): string {
  if ("header" in model) return renderCurrent(model);
  return renderCurrent({ header:{ image:{src:model.abilityImage,alt:model.abilityName}, eyebrow:"Habilidade", title:model.abilityName, context:model.actorName }, description:model.description.trim()?{html:model.description}:undefined, metadata:{items:[{text:model.passive?"Passiva":model.cost?`${model.cost} ${model.resource}`:"Sem custo"},{text:`Execução: ${model.activationLabel}`}]}, rolls:model.rolls.map((r)=>({label:r.label,detail:[r.intent==="damage"?(r.damageType?`Dano · ${getAbilityDamageTypeLabel(r.damageType)}`:"Dano"):r.intent==="healing"?"Cura":"Rolagem genérica",r.nexThreshold===null?null:`NEX ${r.nexThreshold}%`].filter(Boolean).join(" · "),tone:r.intent==="damage"?"damage":r.intent==="healing"?"healing":"effect",roll:{formula:r.formula}})), resourceStatus:model.passive||model.cost<=0?{text:"Sem gasto de recurso",tone:"neutral"}:model.spentResource?{text:`${model.cost} ${model.resource} gastos (${model.resourceBefore} → ${model.resourceAfter})`,tone:"spent"}:{text:`${model.cost} ${model.resource} não descontados`,tone:"not-spent"} });
}
